required = ["github.com/kevinburke/go-bindata"]

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  version = "v5.0.0"
  name = "github.com/nicksrandall/dataloader"

[[constraint]]
  version = "v0.8.0"
  name = "github.com/pkg/errors"

[prune]
  non-go = true
  unused-packages = true
